name: Build FFmpeg (Android, arm64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build FFmpeg for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up dependencies on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake build-essential cmake git-core libass-dev \
            libfreetype6-dev libsdl2-dev libtool libva-dev libvdpau-dev \
            libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev \
            meson ninja-build pkg-config texinfo wget yasm zlib1g-dev

      - name: Clone ffmpeg
        uses: ./.github/actions/ffmpeg-clone

      # Set up Android SDK
      - uses: android-actions/setup-android@v2
      - run: sdkmanager "build-tools;33.0.0"
      - run: sdkmanager "platforms;android-26"
      - run: sdkmanager "platform-tools"
      - run: sdkmanager "ndk;24.0.8215888"

      # Check Android SDK
      - name: Check Android SDK location
        run: echo $ANDROID_HOME
      - name: Check sdkmanager location
        run: which sdkmanager
      - name: Build FFmpeg
        run: |
          cd ffmpeg
          ./configure \
          --enable-shared \
          --enable-static \
          --prefix=out \
          --target-os=android \
          --arch=aarch64 \
          --cpu=armv8-a \
          --cross-prefix=aarch64-linux-android- \
          --enable-cross-compile \
          --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          --cc=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang \
          --cxx=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang++ \
          --ld=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ld \
          --strip=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip \
          --nm=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-nm
          make -j1
          make install

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-android-arm64-v8a
          path: ffmpeg/out
