name: Build FFmpeg (MacOS, Silicon)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build FFmpeg for MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up dependencies on macOS
        run: |
          brew update
          brew install \
            autoconf automake cmake fdk-aac git lame libass libtool \
            libvorbis libvpx opus sdl2 texinfo wget x264 x265 xvid yasm

      - name: Clone ffmpeg
        uses: ./.github/actions/ffmpeg-clone

      - name: Build FFmpeg on MacOS (Silicon, arm64)
        run: |
          cd ffmpeg
          ./configure --enable-shared --enable-static --arch=arm64 --prefix=out-arm64
          make -j1
          make install

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-macos-arm64
          path: ffmpeg/out-arm64
