name: Build FFmpeg

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build FFmpeg for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up dependencies on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake build-essential cmake git-core libass-dev \
            libfreetype6-dev libsdl2-dev libtool libva-dev libvdpau-dev \
            libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev \
            meson ninja-build pkg-config texinfo wget yasm zlib1g-dev

      - name: Set up dependencies on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install \
            autoconf automake cmake fdk-aac git lame libass libtool \
            libvorbis libvpx opus sdl2 texinfo wget x264 x265 xvid yasm

      - name: Set up dependencies on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install make nasm

      - name: Clone FFmpeg
        run: git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg

      - name: Build 5.0
        run: |
          cd ffmpeg
          git checkout n5.0

      - name: Build FFmpeg on Linux and macOS
        if: matrix.os != 'windows-latest'
        run: |
          cd ffmpeg
          ./configure
          make -j$(nproc)

      - name: Build FFmpeg on Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd ffmpeg
          ./configure --toolchain=msvc --arch=x86_64
          make -j$(nproc)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-${{ matrix.os }}
          path: ffmpeg/ffmpeg
