name: Build FFmpeg (Linux, x64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build FFmpeg for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up dependencies on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake build-essential cmake git-core libass-dev \
            libfreetype6-dev libsdl2-dev libtool libva-dev libvdpau-dev \
            libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev \
            meson ninja-build pkg-config texinfo wget yasm zlib1g-dev

      - name: Clone ffmpeg
        uses: ./.github/actions/ffmpeg-clone

      - name: Build FFmpeg
        run: |
          cd ffmpeg
          ./configure --enable-shared --enable-static --prefix=out
          make -j1
          make install

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-linux-x64
          path: ffmpeg/out
