name: Build FFmpeg (Android, arm64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build FFmpeg for Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up dependencies on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf automake build-essential cmake git-core libass-dev \
            libfreetype6-dev libsdl2-dev libtool libva-dev libvdpau-dev \
            libvorbis-dev libxcb1-dev libxcb-shm0-dev libxcb-xfixes0-dev \
            meson ninja-build pkg-config texinfo wget yasm zlib1g-dev

      - name: Clone ffmpeg
        uses: ./.github/actions/ffmpeg-clone

      # Set up Android SDK
      - uses: android-actions/setup-android@v2
      - run: sdkmanager "build-tools;33.0.0"
      - run: sdkmanager "platforms;android-26"
      - run: sdkmanager "platform-tools"
      - run: sdkmanager "ndk;24.0.8215888"

      # Check Android SDK
      - name: Check Android SDK location
        run: echo $ANDROID_HOME
      - name: Check ANDROID_NDK_HOME
        run: echo $ANDROID_NDK_HOME
      - name: Check sdkmanager location
        run: which sdkmanager
      - name: Check name of available tools
        run: ls $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
      - name: Check include path
        run: ls $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
      - name: Are any LDFLAGS set?
        run: echo $LDFLAGS

      - name: Build FFmpeg
        run: |
          cd ffmpeg
          ./configure \
          --enable-shared \
          --enable-pic \
          --disable-debug \
          --disable-programs \
          --disable-hwaccels \
          --disable-inline-asm \
          --disable-network \
          --prefix=out \
          --target-os=android \
          --arch=arm64 \
          --cpu=armv8-a \
          --cross-prefix=aarch64-linux-android- \
          --enable-cross-compile \
          --extra-cflags="-fPIC -I$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include" \
          --extra-ldflags="-fPIC" \
          --sysroot=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
          --cc="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang -fPIC" \
          --cxx="$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang++ -fPIC" \
          --ld=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/ld \
          --ar=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar \
          --nm=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-nm \
          --ranlib=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib \
          --strip=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-strip
          sed  -i "s/#define HAVE_TRUNC 0/#define HAVE_TRUNC 1/" config.h
          sed  -i "s/#define HAVE_TRUNCF 0/#define HAVE_TRUNCF 1/" config.h
          sed  -i "s/#define HAVE_RINT 0/#define HAVE_RINT 1/" config.h
          sed  -i "s/#define HAVE_LRINT 0/#define HAVE_LRINT 1/" config.h
          sed  -i "s/#define HAVE_LRINTF 0/#define HAVE_LRINTF 1/" config.h
          sed  -i "s/#define HAVE_ROUND 0/#define HAVE_ROUND 1/" config.h
          sed  -i "s/#define HAVE_ROUNDF 0/#define HAVE_ROUNDF 1/" config.h
          sed  -i "s/#define HAVE_CBRT 0/#define HAVE_CBRT 1/" config.h
          sed  -i "s/#define HAVE_CBRTF 0/#define HAVE_CBRTF 1/" config.h
          sed  -i "s/#define HAVE_COPYSIGN 0/#define HAVE_COPYSIGN 1/" config.h
          sed  -i "s/#define HAVE_ERF 0/#define HAVE_ERF 1/" config.h
          sed  -i "s/#define HAVE_HYPOT 0/#define HAVE_HYPOT 1/" config.h
          sed  -i "s/#define HAVE_ISNAN 0/#define HAVE_ISNAN 1/" config.h
          sed  -i "s/#define HAVE_ISFINITE 0/#define HAVE_ISFINITE 1/" config.h
          sed  -i "s/#define HAVE_INET_ATON 0/#define HAVE_INET_ATON 1/" config.h
          sed  -i "s/#define getenv(x) NULL/\\/\\/ #define getenv(x) NULL/" config.h
          make -j1
          make install

      - name: Upload config.h
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-config.h
          path: ffmpeg/config.h

      - name: Upload config log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-ffbuild-config.log
          path: ffmpeg/ffbuild/config.log

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-android-arm64-v8a
          path: ffmpeg/out
